version: '3'

services:
  credit-ark-app:
    image: ca
    ports:
      - 8090:8090
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.18.0.1:5432/creditark
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_DATABASE=creditark
      - SPRING_DATASOURCE_PLATFORM=postgres
      - SECURITY_ISSUER_URI=http://172.19.0.1:9080/auth/realms/dev
      - SECURITY_BASIC_ENABLED=false
      - CA_DEFAULT_USER=jgaros
      - CA_SYSTEM_SCENARIO=false
      - CA_SYSTEM_SCENARIO_USER=system_scenario
      - MGMT_SECURITY_ENABLED=true
      - "RECUR_PHASE=0 19 23 1/1 * ?"
      - ENABLE_SCHEDULING=false
      - OAUTH_CLIENT_ID=ca
      - OAUTH_CLIENT_SECRET=48dc567c-0a91-4053-86d4-5c737a48b3e8
      - OAUTH_CLIENT_USER_AUTH_URI=http://172.19.0.1:9080/auth/realms/dev/protocol/openid-connect/auth
      - OAUTH_CLIENT_ACCESS_TOKEN_URI=http://172.19.0.1:9080/auth/realms/dev/protocol/openid-connect/token
      - OAUTH_CLIENT_SCOPE=openid
      - OAUTH_RESOURCE_TOKEN=http://172.19.0.1:9080/auth/realms/dev/protocol/openid-connect/token/introspect
      - JAVA_OPTS=-Xms2G -Xmx6G
      - REPORTS_PATH=F:\\reports
      - CREATE_SCENARIO_REPORT=true
#    logging:
#      driver: syslog
#      options:
#        syslog-address: udp://192.168.65.2:514